# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{juggernaut}
  s.version = "2.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex MacCaw"]
  s.date = %q{2010-12-18}
  s.description = %q{Use Juggernaut to easily implement realtime chat, collaboration, gaming and much more!}
  s.email = %q{info@eribium.org}
  s.files = [
    ".document",
     ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "examples/juggernaut_observer.js",
     "examples/juggernaut_observer.rb",
     "examples/roster.rb",
     "juggernaut.gemspec",
     "lib/juggernaut.rb"
  ]
  s.homepage = %q{http://github.com/maccman/juggernaut}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple realtime push}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, [">= 0"])
    else
      s.add_dependency(%q<redis>, [">= 0"])
    end
  else
    s.add_dependency(%q<redis>, [">= 0"])
  end
end

