#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../config/environment.rb'

logger = RAILS_DEFAULT_LOGGER

class MailerDaemonFetcherDaemon < Daemon::Base
  
  @config = APP_CONFIG['incoming'].to_options
  
  @sleep_time = @config.delete(:sleep_time) || 30
    @fetcher = Fetcher.create({:receiver => Emailer}.merge(@config))
  
  def self.start
    puts "Starting MailerDaemonFetcherDaemon"
    @fetcher = Fetcher.create({:receiver => Emailer}.merge(@config))

    loop do
      @fetcher.fetch
      sleep(@sleep_time)
    end
  end
  
  def self.stop
    puts "Stopping MailerDaemonFetcherDaemon"
  end
  
end

MailerDaemonFetcherDaemon.daemonize